// Generated by https://quicktype.io

interface User {
  _id: string;
  name: string;
  email: string;
  role: string;
  createdAt: string;
  updatedAt: string;
  picture: {
    public_id: string;
    url: string;
  };
}
